### ISSUE TITLE
[suggestion] use JS labels for gotos.

### ISSUE THREAD

**Issue by pygy** [spaceflint7/loulabelle#1]
You could rely on JS labels to implement Lua gotos. They have similar scoping semantics AFAICT, which means that you can translate this:

```Lua
for j = 1, 10 do
  if condition then goto foo end
  -- some code
end
::foo::
-- some more code
if (otherCondition) then goto foo end
```

into this:

```JS
foo: while(true) {
  for(var j = 0; j < 10; j++) {
    if (condition) break foo;
    // some code
  }
  break
}
foo: while(true) {
  // some more code
  if (otherCondition) continue foo
  break
}
```

[Sample here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgAcAnGAPhboBMeAHTRRa1DFAAEEKQF4pABhFhaHKQCt5UgIwVdiqf1oipMsJqncpAJinFCTKQHNaxWlNUem-UzO2yANS6Ij4iiIheESKyCkEhaBAWABSyAGRQxADcUgDsAJT2jmh+nBAMyUIgaDAw-HD2Hs4ctADuUlX6EPl+ru6etCY1aL4laGUVVcY1HZQyPWgsAPQCPMucPCAAvhTo2LiIBBoIVHQMTMR4AG4Y6rFKIiqDiFKthNAwycQcAK4whcA-KoOMkbuotApFDktCwDNDAoEAX4zEkpMktNYbIUAEZcDAAawGtCyyP8cSkwR0fi2flxMAJIhpaCir3esC+v3+UkBaBRAQpCRRKVksIKPLMZjOcFosHwYmclWqtXqjRcLVanXmpLOxHKfyJ1NpePxjMeaClMpgctoCqm9Bgmu62121X2eHw1DgJxo9EYzEO2wAulsgA)

**Comment by spaceflint7** [comment]
Right, I am using JavaScript labels in this way to implement multi-level break and continue.
(Single-level can just break or continue without a label.)
I wrote about it briefly in section 3 of the manual:
https://www.spaceflint.com/loulabelle/manual.html#3
But note that JavaScript labels don't work for arbitrary goto targets.

**Comment by pygy** [comment]
That's the thing, Lua doesn't have arbitrary targets. The labels are block-scoped (so you can't jump into a nested block, nor into the scope of a new local value.

Take this:

```Lua
goto bad
do ::bad:: end
```

The above errors out with `no visible label 'bad' for <goto>`.

Also, this

```Lua
goto bad
local i = 4
::bad::
print(i) -- mandatory for the error, 
```

will give `<goto bad> at line 1 jumps into the scope of local 'i'`

This leaves us with jumps either forward or backwards that stay in the same block or jump out of the current block. They can be covered with labels and `break`/ `continue`.

**Comment by spaceflint7** [comment]
You can have arbitrary goto targets within a block, for example you can skip over statements, and jump back:

```lua
    print "a"
    ::b::
    print "b"
    goto d
    print "c"
    ::d::
    print "d"
    goto b
```

Not sure JavaScript labels would be useful for this type of code.  A switch statement within an infinite loop would be more appropriate:

```javascript
    (function(){
        var lbl="0";
        while (true) {
            switch (lbl) {
                case "0":
                    console.log("a");
                case "b":
                    console.log("b");
                    lbl="d";
                    continue;
                    console.log("c");
                case "d":
                    console.log("d");
                    lbl="b";
                    continue;
            }
        }
    })()
```

So arbitrary gotos are not out of the question, but at this time I do not feel they are important enough to merit adding support for such a switch-loop in the compiler.

**Comment by pygy** [comment]
Ah, yes, it actually dawned on me when I was offline. Jumps that overlap partially can't be implemented with labels, you're right.

Your example can be though:

```JS
console.log("a")
b: while (true) {
  console.log("b");
  d: while (true) {
    break d;
    console.log("c");
    break;
  }
  console.log("d")
  continue b;
  break;
}
```

 but not this:

```Lua
function crossed()
  goto last
  ::first::
  do return 5 end
  ::last::
  goto first
end
crossed() -- 5
```

**Comment by spaceflint7** [comment]
I don't know if it would be trivial to do a control flow analysis on my example, to produce the loop structure that you propose in the first example of your last post.   And as you note in your second example, some flows require the while/switch combo anyway.  So if I do improve the support for goto, I would probably just do the while/switch combo.

By the way, it ocurred to me during our discussion that I messed up multi-level continue a bit.

```lua
for i = 1, 10 do
    while true do
        while true do
            goto cont
        end
    end
    ::cont::
end
```

Translates to:

```javascript
x1=1;
L1:while(x1<=10){
        v1=x1;
        while(true){
                        while(true){
                                        continue L1;
                        }
        }
        x1+=1;
}
```

The "continue L1" skips the increment at the end of the for loop, causing an infinite loop bug.

I'll leave this issue open until I fix this.

**Comment by pygy** [comment]
The cases that don't map to labels + continue/break are those where the jumps overlap partially.

```Lua
::label1:: --------+
--                 |
goto label2 ---+   ^
--             |   |
goto label1 -- v --+
--             |
::label2:: ----+
```

```Lua
goto label1 -------+
--                 |
goto label2 ---+   v
--             |   |
::label1:: --- v --+
--             |
::label2:: ----+
```

Your example had complete overlap:

```Lua
::b:: --------+
--            |
goto d ---+   |
--        v   ^
::d:: ----+   | 
--            |
goto b -------+

```

You'll probaby get better perf if you use labels+break/continue when possible.
